# Generated by Django 2.2 on 2020-03-28 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_auto_20200328_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportecovid',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.UsuarioCovid'),
        ),
    ]
