# Generated by Django 2.2 on 2020-03-28 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_auto_20200328_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportecovid',
            options={'verbose_name': 'Reporte Covid', 'verbose_name_plural': 'Reportes covid'},
        ),
    ]
